language: python
python:
  - "3.6"
  - "2.7"
install:
  - make prepare
  - make develop extras=[all] # adding extras to avoid import errors
script:
  - TOIL_TEST_QUICK=True make test_offline
env:
  - BOTO_CONFIG=null